ALTER TABLE live_config ADD COLUMN IF NOT EXISTS route TEXT NOT NULL DEFAULT 'primary';
ALTER TABLE live_config ADD COLUMN IF NOT EXISTS emergency_stream TEXT NOT NULL DEFAULT '';
ALTER TABLE live_config ADD COLUMN IF NOT EXISTS no_signal_stream TEXT NOT NULL DEFAULT '';
